################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################

if (NOT MSVC)
  include(FindPkgConfig)
  pkg_check_modules(PC_LUA "lua")
  if (NOT PC_LUA_FOUND)
    pkg_check_modules(PC_LUA "lua")
  endif(NOT PC_LUA_FOUND)
  if (PC_LUA_FOUND)
    # some libraries install the headers is a subdirectory of the include dir
    # returned by pkg-config, so use a wildcard match to improve chances of finding
    # headers and SOs.
    set(PC_LUA_INCLUDE_HINTS ${PC_LUA_INCLUDE_DIRS} ${PC_LUA_INCLUDE_DIRS}/*)
    set(PC_LUA_LIBRARY_HINTS ${PC_LUA_LIBRARY_DIRS} ${PC_LUA_LIBRARY_DIRS}/*)
  endif(PC_LUA_FOUND)
endif (NOT MSVC)

find_path(
    LUA_INCLUDE_DIRS
    NAMES lua.h
    HINTS ${PC_LUA_INCLUDE_HINTS}
)

find_library(
    LUA_LIBRARIES
    NAMES lua
    HINTS ${PC_LUA_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  LUA
  REQUIRED_VARS LUA_LIBRARIES LUA_INCLUDE_DIRS
)
mark_as_advanced(LUA_FOUND LUA_LIBRARIES LUA_INCLUDE_DIRS)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
