/*  =========================================================================
    composite-metrics - COMPOSITE-METRICS wrapper

    Copyright (C) 2014 - 2015 Eaton                                        
                                                                           
    This program is free software; you can redistribute it and/or modify   
    it under the terms of the GNU General Public License as published by   
    the Free Software Foundation; either version 2 of the License, or      
    (at your option) any later version.                                    
                                                                           
    This program is distributed in the hope that it will be useful,        
    but WITHOUT ANY WARRANTY; without even the implied warranty of         
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          
    GNU General Public License for more details.                           
                                                                           
    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.            

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef COMPOSITE_METRICS_LIBRARY_H_INCLUDED
#define COMPOSITE_METRICS_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>
#include <lua.h>
#include <biosproto.h>

//  COMPOSITE-METRICS version macros for compile-time API detection

#define COMPOSITE_METRICS_VERSION_MAJOR 0
#define COMPOSITE_METRICS_VERSION_MINOR 1
#define COMPOSITE_METRICS_VERSION_PATCH 0

#define COMPOSITE_METRICS_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define COMPOSITE_METRICS_VERSION \
    COMPOSITE_METRICS_MAKE_VERSION(COMPOSITE_METRICS_VERSION_MAJOR, COMPOSITE_METRICS_VERSION_MINOR, COMPOSITE_METRICS_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBCOMPOSITE_METRICS_STATIC
#       define COMPOSITE_METRICS_EXPORT
#   elif defined LIBCOMPOSITE_METRICS_EXPORTS
#       define COMPOSITE_METRICS_EXPORT __declspec(dllexport)
#   else
#       define COMPOSITE_METRICS_EXPORT __declspec(dllimport)
#   endif
#else
#   define COMPOSITE_METRICS_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _bios_composite_metrics_server_t bios_composite_metrics_server_t;
#define BIOS_COMPOSITE_METRICS_SERVER_T_DEFINED


//  Public API classes
#include "bios_composite_metrics_server.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
